### ISSUE TITLE
PR to PHPUnit

### ISSUE THREAD

**Issue by keradus** [GeckoPackages/PHPUnit#4]
Hi!
Why not to send this new assertions to `phpunit/phpunit` as PR ?

**Comment by SpacePossum** [comment]
Hello :)

I've been thinking about it, since it would make sense :+1:, so I prop. will. 
I'm putting this up, hoping to get feedback from more developers, check how the code does using travis etc.. But the repo should also provide code, documentation and tests which could you use as an example for PR(s) to PHPUnit. So, yes a PR on `phpunit/phpunit` is to expected :)

**Comment by keradus** [comment]
great to hear that! some of the assertion looks really useful !

**Comment by SpacePossum** [comment]
Thanks! keep you posted :)
